import Head from "next/head";

export default function Hhead(): JSX.Element {
  return (
    <>
      {/* <!-- Head --> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <!-- end of Head --> */}
    </>
  );
}
