import React from 'react';
import Head from 'next/head';
import '@/styles/globals.css';
import dynamic from 'next/dynamic';
import type { AppProps } from 'next/app';
import { motion } from 'framer-motion';

const Hero = dynamic(() => import('../../components/hero'), { ssr: false });
const PageView = dynamic(() => import('../../components/PageView'), {
  ssr: false,
});
const Footer = dynamic(() => import('../../components/footer'), { ssr: false });

const variants = {
  hidden: { opacity: 0, x: -200, y: 0 },
  enter: { opacity: 1, x: 0, y: 0 },
};

function Layout({ children }: { children?: any }): JSX.Element {
  return (
    <>
      {/* <!-- Head --> */}
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <!-- end of Head --> */}
      <motion.main
        variants={variants}
        initial='hidden'
        animate='enter'
        transition={{ type: 'linear' }}
      >
        <Hero />

        {/* <!-- main --> */}
        <PageView>{children}</PageView>
        {/* <!-- end of main --> */}
        <Footer />
      </motion.main>
    </>
  );
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
