import Head from 'next/head';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Layout from '../../components/Layout';
import React from 'react';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      {/* <!-- Head --> */}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <!-- end of Head --> */}

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
