'use client';

import React from 'react';
import Head from 'next/head';
import '@/styles/globals.scss';
import { AppProps } from 'next/app';
import Layout from '@/components/Layout';

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <>
      {/* <!-- Head --> */}
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <!-- end of Head --> */}
      <Layout router={router}>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
