import React from 'react';
import Head from 'next/head';
import PageView from '../components/PageView';

export default function Home() {
  return (
    <>
      {/* <!-- Head --> */}
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <!-- end of Head --> */}
      <PageView>
        {/* <!-- section --> */}
        <section className='section single-page'>
          <div className='section-title'>
            <h1>about me</h1>
            <div className='underline'></div>
          </div>
          <div className='section-center page-info'>
            <p>
              Hi there 👋I&#x27;m Ghazi Ramadan form the United States of 🇺🇸
              American.
              <br />I studied computer science, applied maths, pure maths, and
              data science. I&#x27;m also an artist, game maker, DevOpsSec, and
              graph designer with programming (and creative coding in general)
              in my free time. Professional Landscape Designer with several
              years of experience working with clients to create and enhance the
              aesthetics and function of natural outdoor spaces. The ability to
              understand and fulfill a client&#x27;s vision is what sets us
              apart as a design and horticulture company. Design, manage, and
              plan projects of all sizes, from small to very large. My
              communication and collaboration skills make me a dynamic,
              dedicated professional. Thank you 🦕
            </p>
          </div>
        </section>
        {/* <!-- end of section --> */}
      </PageView>
    </>
  );
}
