import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* <!-- navbar --> */}
        <nav className="nav" id="nav">
          <div className="nav-center">
            {/* <!-- nav header --> */}
            <div className="nav-header">
              {/* <Image src="./images/logo.svg" className="nav-logo" alt="" width={100} /> */}
              <button className="nav-btn" id="nav-btn">
                <i className="fas fa-bars"></i>
              </button>
            </div>
            {/* <!-- nav links --> */}
            <ul className="nav-links">
              <li>
                <a href="index.html">home</a>
              </li>
              <li>
                <a href="about.html">about</a>
              </li>
              <li>
                <a href="projects.html">projects</a>
              </li>
              <li>
                <a href="contact.html">contact</a>
              </li>
            </ul>
          </div>
        </nav>
        {/* <!-- end of navbar -->*/}
        {/* <!-- sidebar --> */}
        <aside className="sidebar" id="sidebar">
          <div>
            <button id="close-btn" className="close-btn">
              <i className="fas fa-times"></i>
            </button>
            <ul className="sidebar-links">
              <li>
                <a href="index.html">home</a>
              </li>
              <li>
                <a href="about.html">about</a>
              </li>
              <li>
                <a href="projects.html">projects</a>
              </li>
              <li>
                <a href="contact.html">contact</a>
              </li>
            </ul>
            <ul className="social-icons">
              {/* <!-- single item --> */}
              <li>
                <a href="https://www.twitter.com" className="social-icon">
                  <i className="fab fa-facebook"></i>
                </a>
              </li>
              {/* <!-- end of single item --> */}
              {/* <!-- single item --> */}
              <li>
                <a href="https://www.twitter.com" className="social-icon">
                  <i className="fab fa-linkedin"></i>
                </a>
              </li>
              {/* <!-- end of single item --> */}
              {/* <!-- single item --> */}
              <li>
                <a href="https://www.twitter.com" className="social-icon">
                  <i className="fab fa-squarespace"></i>
                </a>
              </li>
              {/* <!-- end of single item --> */}
              {/* <!-- single item --> */}
              <li>
                <a href="https://www.twitter.com" className="social-icon">
                  <i className="fab fa-behance"></i>
                </a>
              </li>
              {/* <!-- end of single item --> */}
              {/* <!-- single item --> */}
              <li>
                <a href="https://www.twitter.com" className="social-icon">
                  <i className="fab fa-instagram"></i>
                </a>
              </li>
              {/* <!-- end of single item --> */}
            </ul>
          </div>
        </aside>
        {/* <!-- end of sidebar --> */}

        <section className="section single-page">
          <div className="section-title">
            <h1>about me</h1>
            <div className="underline"></div>
          </div>
          <div className="section-center page-info">
            <p>
              {" "}
              <a href="https://www.youtube.com/channel/UCMZFwxv5l-XtKi693qMJptA">
                Hi there 👋I&#x27;m Ghazi Ramadan form the United States of 🇺🇸
                American.
              </a>
              <br />I studied computer science, applied maths, pure maths, and
              data science. I’m also an artist, game maker, DevOpsSec, and graph
              designer with programming (and creative coding in general) in my
              free time. Professional Landscape Designer with several years of
              experience working with clients to create and enhance the
              aesthetics and function of natural outdoor spaces. The ability to
              understand and fulfill a client&#x27;s vision is what sets us
              apart as a design and horticulture company. Design, manage, and
              plan projects of all sizes, from small to very large. My
              communication and collaboration skills make me a dynamic,
              dedicated professional. Thank you 🦕
            </p>
          </div>
        </section>

        {/* <!-- footer --> */}
        <footer className="footer">
          <ul className="social-icons">
            {/* <!-- single item --> */}
            <li>
              <a href="https://www.twitter.com" className="social-icon">
                <i className="fab fa-facebook"></i>
              </a>
            </li>
            {/* <!-- end of single item --> */}
            {/* <!-- single item --> */}
            <li>
              <a href="https://www.twitter.com" className="social-icon">
                <i className="fab fa-linkedin"></i>
              </a>
            </li>
            {/* <!-- end of single item --> */}
            {/* <!-- single item --> */}
            <li>
              <a href="https://www.twitter.com" className="social-icon">
                <i className="fab fa-squarespace"></i>
              </a>
            </li>
            {/* <!-- end of single item --> */}
            {/* <!-- single item --> */}
            <li>
              <a href="https://www.twitter.com" className="social-icon">
                <i className="fab fa-behance"></i>
              </a>
            </li>
            {/* <!-- end of single item --> */}
            {/* <!-- single item --> */}
            <li>
              <a href="https://www.twitter.com" className="social-icon">
                <i className="fab fa-instagram"></i>
              </a>
            </li>
            {/* <!-- end of single item --> */}
          </ul>

          <p>
            &copy; <span id="date"></span>
            ghazi ramadan. All rights reserved.
          </p>
        </footer>
      </main>
    </>
  );
}
